use std::time::{Instant, Duration};
use std::thread;
use std::io::{Write, stdout, StdoutLock, BufWriter};

pub struct Timer {
    clk_ns: u64,
    start: Option<Instant>,
    bg_start: Option<Instant>,
}

impl Timer {
    pub fn new(clk_us: u64) -> Self {
        Self {
            clk_ns: clk_us * 1000,
            start: None,
            bg_start: None,
        }
    }

    pub fn bg(&mut self) {
        let now = Instant::now();
        self.bg_start = Some(now);
        self.start = Some(now);
    }

    /// Returns the number of frames that should have passed since start.
    /// Used for frame skipping to maintain sync with audio.
    pub fn get_target_frame(&self) -> u64 {
        if let Some(bg) = self.bg_start {
            let elapsed = bg.elapsed().as_nanos() as u64;
            elapsed / self.clk_ns
        } else {
            0
        }
    }

    pub fn wait(&mut self) {
        if let Some(start) = self.start {
            let target = Duration::from_nanos(self.clk_ns);
            let now = Instant::now();
            
            if now < start + target {
                thread::sleep((start + target).duration_since(now));
            }
            
            // Sync start to current frame slot
            self.start = Some(start + target);
        }
    }
}

pub struct Printer {
    timer: Timer,
    not_clear: bool,
    writer: BufWriter<StdoutLock<'static>>,
}

impl Printer {
    pub fn new(clk_us: u64, not_clear: bool) -> Self {
        let mut timer = Timer::new(clk_us);
        
        let stdout_obj = Box::leak(Box::new(stdout()));
        let mut lock = stdout_obj.lock();
        
        if not_clear {
            writeln!(lock).unwrap();
        } else {
            write!(lock, "\x1b[?25l\x1b[2J\x1b[H").unwrap(); // Hide cursor, clear screen, move home
        }
        lock.flush().unwrap();
        
        timer.bg();
        
        Self {
            timer,
            not_clear,
            writer: BufWriter::with_capacity(1024 * 1024, lock), // 1MB Buffer
        }
    }

    pub fn print_a_frame(&mut self, buffer: &[u8]) {
        if !self.not_clear {
            let _ = write!(self.writer, "\x1b[H"); // Move home
        }
        let _ = self.writer.write_all(buffer);
        let _ = self.writer.flush();
        
        self.timer.wait();
    }

    pub fn get_target_frame(&self) -> u64 {
        self.timer.get_target_frame()
    }
}

use std::fs::File;

pub struct Preloader {
    fp: File,
}

impl Preloader {
    pub fn new(output: &str, x: i32, y: i32, clk: u64) -> Result<Self, String> {
        let mut fp = File::create(output).map_err(|e| format!("Open output file failed: {}", e))?;
        
        // Write header: "width (height/2) clk\n"
        write!(fp, "{} {} {}\n", x, y / 2, clk).map_err(|e| e.to_string())?;
        
        Ok(Self { fp })
    }

    pub fn print_a_frame(&mut self, buffer: &[u8]) {
        let _ = self.fp.write_all(buffer);
    }
}

pub struct ReactExporter {
    output: String,
    frames: Vec<String>,
    fps: f64,
    audio_base64: Option<String>,
    audio_type: String,
}

impl ReactExporter {
    pub fn new(output: &str, fps: f64, audio_base64: Option<String>, audio_type: &str) -> Self {
        Self {
            output: output.to_string(),
            frames: Vec::new(),
            fps,
            audio_base64,
            audio_type: audio_type.to_string(),
        }
    }

    pub fn add_frame(&mut self, buffer: &[u8]) {
        let s = String::from_utf8_lossy(buffer).to_string();
        
        // Strip ANSI escape codes (e.g., \x1b[38;2;...m, \x1b[0m)
        // This ensures the React component renders clean text without visible escape sequences.
        let ansi_regex = regex::Regex::new(r"\x1b\[[0-9;]*m").unwrap();
        let stripped = ansi_regex.replace_all(&s, "").to_string();
        
        self.frames.push(stripped);
    }

    pub fn save(self) -> std::io::Result<()> {
        let mut fp = File::create(&self.output)?;
        
        let frames_json = serde_json::to_string(&self.frames)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e))?;

        let audio_src = if let Some(ref b64) = self.audio_base64 {
            format!("data:{};base64,{}", self.audio_type, b64)
        } else {
            "".to_string()
        };

        let template = format!(r#"
import React, {{ useState, useEffect, useRef }} from 'react';

/**
 * BadAppleAnim Component (Audio Enabled)
 * Generated by Bad-Apple-RS
 */
const frames: string[] = {};
const AUDIO_SRC = "{}";

export const BadAppleAnim: React.FC = () => {{
    const [currentFrame, setCurrentFrame] = useState(0);
    const [started, setStarted] = useState(false);
    const [zoom, setZoom] = useState(6);
    const [filter, setFilter] = useState('#0f0');
    const [scanlines, setScanlines] = useState(true);
    const audioRef = useRef<HTMLAudioElement>(null);
    const fps = {};

    useEffect(() => {{
        if (!started) return;

        const interval = setInterval(() => {{
            if (audioRef.current) {{
                const time = audioRef.current.currentTime;
                const targetFrame = Math.floor(time * fps);
                setCurrentFrame(prev => {{
                    if (targetFrame < frames.length) return targetFrame;
                    return prev;
                }});
            }} else {{
                setCurrentFrame(prev => (prev + 1) % frames.length);
            }}
        }}, 1000 / fps);

        return () => clearInterval(interval);
    }}, [fps, started]);

    const handleStart = () => {{
        setStarted(true);
        if (audioRef.current) {{
            audioRef.current.play().catch(e => console.error("Autoplay blocked:", e));
        }}
    }};

    return (
        <div style={{{{
            backgroundColor: '#050505',
            color: filter,
            fontFamily: '"Courier New", Courier, monospace',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            minHeight: '100vh',
            overflow: 'hidden',
            position: 'relative'
        }}}}>
            
            {/* Background Grid */}
            <div style={{{{
                position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
                backgroundImage: `linear-gradient(${filter}22 1px, transparent 1px), linear-gradient(90deg, ${filter}22 1px, transparent 1px)`,
                backgroundSize: '40px 40px',
                zIndex: 0
            }}}} />

            {!started && (
                <div style={{{{
                    position: 'absolute',
                    zIndex: 100,
                    backgroundColor: 'rgba(0,0,0,0.9)',
                    padding: '60px',
                    border: `2px solid ${{filter}}`,
                    borderRadius: '5px',
                    textAlign: 'center',
                    boxShadow: `0 0 40px ${{filter}}`,
                    backdropFilter: 'blur(10px)'
                }}}} onClick={{handleStart}}>
                    <h1 style={{{{ margin: '0 0 10px 0', fontSize: '48px', letterSpacing: '10px' }}}}>BAD APPLE!!</h1>
                    <div style={{{{ marginBottom: '30px', opacity: 0.6, fontSize: '12px' }}}}>[ SYSTEM INITIALIZED | VERSION 2.2.0 ]</div>
                    <button 
                        style={{{{
                            backgroundColor: filter,
                            color: '#000',
                            border: 'none',
                            padding: '15px 40px',
                            fontSize: '24px',
                            fontWeight: 'bold',
                            cursor: 'pointer',
                            boxShadow: `0 0 20px ${{filter}}`
                        }}}}
                    >
                        START UPLINK
                    </button>
                    <p style={{{{ marginTop: '20px', fontSize: '12px' }}}}>Click to synchronize neural audio-visual data</p>
                </div>
            )}

            {/* DASHBOARD UI */}
            <div style={{{{
                zIndex: 10,
                width: '90%',
                maxWidth: '1200px',
                display: 'flex',
                flexDirection: 'column',
                gap: '20px'
            }}}}>
                {/* Header Info */}
                <div style={{{{ display: 'flex', justifyContent: 'space-between', borderBottom: `1px solid ${{filter}}44`, paddingBottom: '10px' }}}}>
                    <div>LOG://BAD_APPLE.EXE</div>
                    <div style={{{{ opacity: 0.8 }}}}>STATUS: {{started ? 'STREAMING' : 'IDLE'}} | FRAME: {{currentFrame}} / {{frames.length}}</div>
                </div>

                {/* Main Viewport */}
                <div style={{{{
                    position: 'relative',
                    border: `1px solid ${{filter}}88`,
                    backgroundColor: '#000',
                    padding: '20px',
                    overflow: 'auto',
                    display: 'flex',
                    justifyContent: 'center',
                    boxShadow: `inset 0 0 50px rgba(0,0,0,1), 0 0 20px ${{filter}}22`,
                }}}}>
                     <audio ref={{audioRef}} src={{AUDIO_SRC}} loop />
                     
                     {scanlines && (
                         <div style={{{{
                            position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
                            background: 'linear-gradient(rgba(18, 16, 16, 0) 50%, rgba(0, 0, 0, 0.25) 50%)',
                            backgroundSize: '100% 4px',
                            pointerEvents: 'none',
                            zIndex: 5
                         }}}} />
                     )}

                     <pre 
                         style={{{{
                             fontSize: `${{zoom}}px`,
                             lineHeight: '1.0',
                             whiteSpace: 'pre',
                             margin: 0,
                             filter: `drop-shadow(0 0 5px ${{filter}})`,
                             animation: 'bad-apple-flicker 0.15s infinite',
                             transition: 'font-size 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
                             userSelect: 'none',
                             opacity: started ? 1 : 0.1
                         }}}}
                     >
                         {{frames[currentFrame]}}
                     </pre>
                </div>

                {/* Control Panel */}
                <div style={{{{
                    display: 'grid',
                    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
                    gap: '20px',
                    border: `1px solid ${{filter}}44`,
                    padding: '20px',
                    backgroundColor: 'rgba(0,255,0,0.02)'
                }}}}>
                    <div>
                        <label style={{{{ display: 'block', fontSize: '10px', marginBottom: '5px' }}}}>UPLINK ZOOM (FONT SIZE)</label>
                        <input type="range" min="2" max="15" value={{zoom}} onChange={{(e) => setZoom(Number(e.target.value))}} 
                               style={{{{ width: '100%', accentColor: filter }}}} />
                    </div>
                    <div>
                        <label style={{{{ display: 'block', fontSize: '10px', marginBottom: '5px' }}}}>VISUAL FILTER</label>
                        <div style={{{{ display: 'flex', gap: '10px' }}}}>
                            {['#0f0', '#ffb000', '#00ffff', '#fff'].map(c => (
                                <div key={{c}} onClick={{() => setFilter(c)}} 
                                     style={{{{ width: '20px', height: '20px', background: c, border: filter === c ? '2px solid white' : 'none', cursor: 'pointer' }}}} />
                            ))}
                        </div>
                    </div>
                    <div>
                        <label style={{{{ display: 'block', fontSize: '10px', marginBottom: '5px' }}}}>HARDWARE EMULATION</label>
                        <button onClick={{() => setScanlines(!scanlines)}} 
                                style={{{{ background: 'transparent', color: filter, border: `1px solid ${{filter}}`, padding: '5px 10px', cursor: 'pointer', fontSize: '10px' }}}}>
                            SCANLINES: {{scanlines ? 'ON' : 'OFF'}}
                        </button>
                    </div>
                </div>
                
                <div style={{{{ fontSize: '9px', opacity: 0.5, textAlign: 'center' }}}}>
                    WARNING: NEURAL LINK ESTABLISHED. PROCEED WITH CAUTION. DO NOT DISCONNECT POWER.
                </div>
            </div>

            <style>
                {{`
                    @keyframes bad-apple-flicker {{
                        0% {{ opacity: 0.98; }}
                        50% {{ opacity: 1; }}
                        100% {{ opacity: 0.99; }}
                    }}
                    body {{ margin: 0; background: #050505; color: white; -webkit-font-smoothing: none; }}
                    input[type=range] {{ cursor: pointer; }}
                `}}
            </style>
        </div>
    );
}};

export default BadAppleAnim;
"#, frames_json, audio_src, self.fps);

        fp.write_all(template.as_bytes())?;
        println!("React component saved to: {}", self.output);
        Ok(())
    }
}

pub struct WebStreamer {
    tx: tokio::sync::broadcast::Sender<String>,
}

impl WebStreamer {
    pub fn new(tx: tokio::sync::broadcast::Sender<String>) -> Self {
        Self { tx }
    }

    pub fn add_frame(&self, buffer: &[u8]) {
        let s = String::from_utf8_lossy(buffer).to_string();
        
        // Strip ANSI escape codes for clean browser rendering
        let ansi_regex = regex::Regex::new(r"\x1b\[[0-9;]*m").unwrap();
        let stripped = ansi_regex.replace_all(&s, "").to_string();
        
        // Broadcast the frame
        let _ = self.tx.send(stripped);
    }
}
